package Consumer.model;

public class LiftRide {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column liftride.liftride_id
     *
     * @mbg.generated Thu Mar 28 16:01:19 CST 2024
     */
    private Integer liftrideId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column liftride.skier_id
     *
     * @mbg.generated Thu Mar 28 16:01:19 CST 2024
     */
    private Integer skierId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column liftride.resort_id
     *
     * @mbg.generated Thu Mar 28 16:01:19 CST 2024
     */
    private Integer resortId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column liftride.lift_id
     *
     * @mbg.generated Thu Mar 28 16:01:19 CST 2024
     */
    private Integer liftId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column liftride.season_id
     *
     * @mbg.generated Thu Mar 28 16:01:19 CST 2024
     */
    private Integer seasonId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column liftride.day_id
     *
     * @mbg.generated Thu Mar 28 16:01:19 CST 2024
     */
    private Integer dayId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column liftride.time
     *
     * @mbg.generated Thu Mar 28 16:01:19 CST 2024
     */
    private Integer time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column liftride.liftride_id
     *
     * @return the value of liftride.liftride_id
     *
     * @mbg.generated Thu Mar 28 16:01:19 CST 2024
     */
    public Integer getLiftrideId() {
        return liftrideId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column liftride.liftride_id
     *
     * @param liftrideId the value for liftride.liftride_id
     *
     * @mbg.generated Thu Mar 28 16:01:19 CST 2024
     */
    public void setLiftrideId(Integer liftrideId) {
        this.liftrideId = liftrideId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column liftride.skier_id
     *
     * @return the value of liftride.skier_id
     *
     * @mbg.generated Thu Mar 28 16:01:19 CST 2024
     */
    public Integer getSkierId() {
        return skierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column liftride.skier_id
     *
     * @param skierId the value for liftride.skier_id
     *
     * @mbg.generated Thu Mar 28 16:01:19 CST 2024
     */
    public void setSkierId(Integer skierId) {
        this.skierId = skierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column liftride.resort_id
     *
     * @return the value of liftride.resort_id
     *
     * @mbg.generated Thu Mar 28 16:01:19 CST 2024
     */
    public Integer getResortId() {
        return resortId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column liftride.resort_id
     *
     * @param resortId the value for liftride.resort_id
     *
     * @mbg.generated Thu Mar 28 16:01:19 CST 2024
     */
    public void setResortId(Integer resortId) {
        this.resortId = resortId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column liftride.lift_id
     *
     * @return the value of liftride.lift_id
     *
     * @mbg.generated Thu Mar 28 16:01:19 CST 2024
     */
    public Integer getLiftId() {
        return liftId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column liftride.lift_id
     *
     * @param liftId the value for liftride.lift_id
     *
     * @mbg.generated Thu Mar 28 16:01:19 CST 2024
     */
    public void setLiftId(Integer liftId) {
        this.liftId = liftId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column liftride.season_id
     *
     * @return the value of liftride.season_id
     *
     * @mbg.generated Thu Mar 28 16:01:19 CST 2024
     */
    public Integer getSeasonId() {
        return seasonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column liftride.season_id
     *
     * @param seasonId the value for liftride.season_id
     *
     * @mbg.generated Thu Mar 28 16:01:19 CST 2024
     */
    public void setSeasonId(Integer seasonId) {
        this.seasonId = seasonId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column liftride.day_id
     *
     * @return the value of liftride.day_id
     *
     * @mbg.generated Thu Mar 28 16:01:19 CST 2024
     */
    public Integer getDayId() {
        return dayId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column liftride.day_id
     *
     * @param dayId the value for liftride.day_id
     *
     * @mbg.generated Thu Mar 28 16:01:19 CST 2024
     */
    public void setDayId(Integer dayId) {
        this.dayId = dayId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column liftride.time
     *
     * @return the value of liftride.time
     *
     * @mbg.generated Thu Mar 28 16:01:19 CST 2024
     */
    public Integer getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column liftride.time
     *
     * @param time the value for liftride.time
     *
     * @mbg.generated Thu Mar 28 16:01:19 CST 2024
     */
    public void setTime(Integer time) {
        this.time = time;
    }
}