package Consumer.mapper;

import Consumer.model.LiftRide;
import Consumer.model.LiftRideExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LiftRideMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table liftride
     *
     * @mbg.generated Thu Mar 28 16:01:19 CST 2024
     */
    long countByExample(LiftRideExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table liftride
     *
     * @mbg.generated Thu Mar 28 16:01:19 CST 2024
     */
    int deleteByExample(LiftRideExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table liftride
     *
     * @mbg.generated Thu Mar 28 16:01:19 CST 2024
     */
    int deleteByPrimaryKey(Integer liftrideId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table liftride
     *
     * @mbg.generated Thu Mar 28 16:01:19 CST 2024
     */
    int insert(LiftRide record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table liftride
     *
     * @mbg.generated Thu Mar 28 16:01:19 CST 2024
     */
    int insertSelective(LiftRide record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table liftride
     *
     * @mbg.generated Thu Mar 28 16:01:19 CST 2024
     */
    List<LiftRide> selectByExample(LiftRideExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table liftride
     *
     * @mbg.generated Thu Mar 28 16:01:19 CST 2024
     */
    LiftRide selectByPrimaryKey(Integer liftrideId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table liftride
     *
     * @mbg.generated Thu Mar 28 16:01:19 CST 2024
     */
    int updateByExampleSelective(@Param("record") LiftRide record, @Param("example") LiftRideExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table liftride
     *
     * @mbg.generated Thu Mar 28 16:01:19 CST 2024
     */
    int updateByExample(@Param("record") LiftRide record, @Param("example") LiftRideExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table liftride
     *
     * @mbg.generated Thu Mar 28 16:01:19 CST 2024
     */
    int updateByPrimaryKeySelective(LiftRide record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table liftride
     *
     * @mbg.generated Thu Mar 28 16:01:19 CST 2024
     */
    int updateByPrimaryKey(LiftRide record);
}